config/routes.rb
Rails.application.routes.draw do
  root 'workhorses#index'
  get 'workhorses/index'

  get 'workhorses/events'

  get 'workhorses/announcements'

  get 'workhorses/bio'

  get 'workhorses/music'

  get 'workhorses/photos'

  get 'workhorses/voice_overs'

  get 'workhorses/contact'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/workhorse.rb
class Workhorse < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workhorses_controller.rb
class WorkhorsesController < ApplicationController
  def index

  end

  def events
    @events = Event.all
  end

  def announcements
  end

  def bio
    
  end

  def music
  end

  def photos
  end

  def voice_overs
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workhorses_helper.rb
module WorkhorsesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <script>
        $(document).ready(function(){

         $('#logo').click(function(){  
         }).bind('ajax:success', function(){
          alert('test logo');
        }); 

         $('#eventz').click(function(){
          ev.preventDefault();  
        }).bind('ajax:success', function(){
          alert('test'); 
        }).bind('ajax:error', function(){
          alert('error');
        });

        $('#bio1').click(function(ev){
          ev.preventDefault();  
        }).bind('ajax:success', function(evt, data, status, xhr){
         // $('.placemat').html(data);
      
          console.log(xhr.responseText);
        });



      });
      </script>

      <%= link_to "TUTTI DRUYAN", root_path, remote: true, id: "logo" %>
      <nav>
        <ul></ul>
        <ul class="nav pull-left">
          <li><%= link_to "Events", workhorses_events_path, remote: true, id: 'eventz' %></li>
          <li><%= link_to "Announcements", workhorses_announcements_path %></li>
          <li><%= link_to "Bio", root_path, remote: true, id: 'bio1' %></li>
          <li><%= link_to "Music", workhorses_music_path %></li>
          <li><%= link_to "Photos", workhorses_photos_path %></li>
          <li><%= link_to "Voice Overs", workhorses_voice_overs_path %></li>
          <li><%= link_to "Contact", workhorses_contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tutti Druyan</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/header' %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/workhorses/announcements.html.erb
<h1>Workhorses#announcements</h1>
<p>Find me in app/views/workhorses/announcements.html.erb</p>

app/views/workhorses/bio.html.erb
<h1>Workhorses#bio</h1>

app/views/workhorses/contact.html.erb
<h1>Workhorses#contact</h1>
<p>Find me in app/views/workhorses/contact.html.erb</p>

app/views/workhorses/events.html.erb
<h1>Workhorses#events</h1>
<% @events.each do |x| %>
	<div class="placemat">
	<div class="text_column">
		<%= x.title %><br><br><br><br><br><br><br><br>
		<%= x.time %><br>
		<%= x.duration %><br>
	</div>
	<div class="picture_column"><%= image_tag x.img %></div>
	</div>
<% end %>

app/views/workhorses/index.html.erb
<div class="placemat">
	<script>
		$(document).ready(function(){
			$( '#slider1' ).lemmonSlider();
		});
	</script>

	<div id="slider1" class="slider">
		<ul>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277df70e4b069a82eaf340c/1383587738479/IMG_0974.JPG?format=750w" alt=""></li>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277dface4b069a82eaf346d/1383587776224/Tutti1.jpg?format=500w" alt=""></li>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277e033e4b0af356e29edaa/1383587903152/TUTTI%20DRUYAN1.jpg?format=500w" alt=""></li>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277deb2e4b0c2eac22f44a2/1383587565825/IMG_0973.JPG?format=750w" alt=""></li>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277de8ae4b0c2eac22f444f/1383587493214/Tutti2.jpg?format=500w" alt=""></li>
			<li><img src="http://static.squarespace.com/static/526df583e4b0a46a4604d41d/52773ef8e4b0a439bc1e3658/5277de76e4b0c2eac22f442c/1383587458014/DA2R1812.jpg?format=500w" alt=""></li>
		</ul>
	</div>
	<div class="controls">
		<button type="button" class="btn btn-default btn-lg prev-slide">
			<span class="icon-chevron-left"></span>
		</button>
		<button type="button" class="btn btn-default btn-lg next-slide">
			<span class="icon-chevron-right"></span> 
		</button>
	</div>
</div>

app/views/workhorses/music.html.erb
<h1>Workhorses#music</h1>
<p>Find me in app/views/workhorses/music.html.erb</p>

app/views/workhorses/photos.html.erb
<h1>Workhorses#photos</h1>
<p>Find me in app/views/workhorses/photos.html.erb</p>

app/views/workhorses/voice_overs.html.erb
<h1>Workhorses#voice_overs</h1>
<p>Find me in app/views/workhorses/voice_overs.html.erb</p>